baseurl = "http://amanewgirl.github.io"
languageCode = "en-us"
title = "Arcade"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  subtitle = "Argumentation Card Games"
  logo = "img/arg_icon_2.png"
  favicon = "ico/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
[[Params.bigimg]]
  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = ""
  email = "40071697@live.napier.ac.uk"
#  facebook = "username"
#  googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "amanewgirl"
#  twitter = "simonwells"
#  reddit = "username"
#  linkedin = "username"
#  xing = "username"
#  stackoverflow = "users/XXXXXXX/username"
#  snapchat = "username"
#  instagram = "username"
#  youtube = "user/username" # or channel/channelname
#  soundcloud = "username"
#  spotify = "username"
#  bandcamp = "username"
#  itchio = "username"

[[menu.main]]
    name = "people"
    url = "/page/people"
    weight = 1

    [[menu.main]]
        parent = "people"
        name = "Dr Simon Wells"
        url = "/page/people/simon-wells/"
        weight = 1

    [[menu.main]]
        parent = "people"
        name = "Dana Khartabil"
        url = "/page/people/dana-khartabil/"
        weight = 2

    [[menu.main]]
        parent = "people"
        name = "affiliate members"
        url = "/page/people/affiliates/"
        weight = 3

    [[menu.main]]
        parent = "people"
        name = "past members"
        url = "/page/people/past/"
        weight = 4


[[menu.main]]
    identifier = "projects"
    name = "Projects"
    weight = 2

    [[menu.main]]
        parent = "projects"
        name = "Argument Cartography"
        url = "/page/project/argument-cartography/"
        weight = 1

    [[menu.main]]
        parent = "projects"
        name = "ArgDB"
        url = "/page/project/argdb/"
        weight = 2

    [[menu.main]]
        parent = "projects"
        name = "DGDL"
        url = "/page/project/dgdl/"
        weight = 3

    [[menu.main]]
        parent = "projects"
        name = "ADAMANT"
        url = "/page/project/adamant/"
        weight = 4

    [[menu.main]]
        parent = "projects"
        name = "SADFace"
        url = "/page/project/sadface/"
        weight = 5

    [[menu.main]]
        parent = "projects"
        name = "Alias"
        url = "/page/project/alias/"
        weight = 6

    [[menu.main]]
        parent = "projects"
        name = "MonkeyPuzzle"
        url = "/page/project/monkeypuzzle/"
        weight = 7

    [[menu.main]]
        parent = "projects"
        name = "Ar:Ca:De"
        url = "/page/project/arcade/"
        weight = 8

[[menu.main]]
    name = "outputs"
    url = "/page/outputs/"
    weight = 3

    [[menu.main]]
        parent = "outputs"
        name = "Publications"
        url = "/page/outputs/publications/"
        weight = 1

    [[menu.main]]
        parent = "outputs"
        name = "datasets"
        url = "/page/outputs/datasets/"
        weight = 2

[[menu.main]]
    name = "admin"
    url = "/page/admin/"
    weight = 4

    [[menu.main]]
        parent = "admin"
        name = "working with us"
        url = "/page/admin/collaboration/"
        weight = 1

    [[menu.main]]
        parent = "admin"
        name = "travel"
        url = "/page/admin/travel/"
        weight = 2

    [[menu.main]]
        parent = "admin"
        name = "vacancies"
        url = "/page/admin/vacancies/"
        weight = 3


